Controllers/ArtistsController.cs
using Microsoft.AspNetCore.Mvc;
using GrammyAwards.Interfaces;
using GrammyAwards.Models;
using System.Threading.Tasks;

namespace GrammyAwards.Controllers
{
    public class ArtistsController : Controller
    {
        private readonly IArtistService _artistService;

        public ArtistsController(IArtistService artistService)
        {
            _artistService = artistService;
        }

        // GET: Artist/Index
        public async Task<IActionResult> Index()
        {
            var artists = await _artistService.GetAllArtistsAsync();
            ViewBag.Artists = artists; // Using ViewBag to pass data to the view
            return View(artists);
        }

        // GET: Artist/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var artist = await _artistService.GetArtistByIdAsync(id);
            if (artist == null)
            {
                throw new Exception("Artist not found"); // Throw exception if artist is not found
            }

            ViewData["Artist"] = artist; // Using ViewData to pass data to the view
            return View(artist);
        }

        // GET: Artist/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Artist/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Artist artist)
        {
            if (ModelState.IsValid)
            {
                await _artistService.AddArtistAsync(artist);
                return RedirectToAction(nameof(Index));
            }

            ViewBag.ErrorMessage = "Invalid data provided."; // Using ViewBag for error messages
            return View(artist);
        }

        // GET: Artist/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var artist = await _artistService.GetArtistByIdAsync(id);
            if (artist == null)
            {
                throw new Exception("Artist not found"); // Throw exception if artist is not found
            }

            ViewBag.Artist = artist; // Using ViewBag to pass data to the view
            return View(artist);
        }

        // POST: Artist/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Artist artist)
        {
            if (id != artist.Id)
            {
                throw new Exception("Artist ID mismatch"); // Throw exception if IDs don't match
            }

            if (ModelState.IsValid)
            {
                await _artistService.UpdateArtistAsync(artist);
                return RedirectToAction(nameof(Index));
            }

            ViewBag.ErrorMessage = "Invalid data provided."; // Using ViewBag for error messages
            return View(artist);
        }

        // GET: Artist/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var artist = await _artistService.GetArtistByIdAsync(id);
            if (artist == null)
            {
                throw new Exception("Artist not found"); // Throw exception if artist is not found
            }

            ViewData["Artist"] = artist; // Using ViewData to pass data to the view
            return View(artist);
        }

        // POST: Artist/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _artistService.DeleteArtistAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/AwardController.cs
using Microsoft.AspNetCore.Mvc;
using GrammyAwards.Interfaces;
using GrammyAwards.Models;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GrammyAwards.Controllers
{
    public class AwardsController : Controller
    {
        private readonly IAwardService _awardService;
        private readonly ISongService _songService;
        private readonly IArtistService _artistService;

        public AwardsController(IAwardService awardService, ISongService songService, IArtistService artistService)
        {
            _awardService = awardService;
            _songService = songService;
            _artistService = artistService;
        }

        // GET: Awards/Index
        public async Task<IActionResult> Index()
        {
            var awards = await _awardService.GetAllAwardsAsync();
            return View(awards); // Returns /Views/Awards/Index.cshtml
        }

        // GET: Awards/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var award = await _awardService.GetAwardByIdAsync(id);
            if (award == null)
            {
                return NotFound();
            }
            return View(award); // Returns /Views/Awards/Details.cshtml
        }

        // GET: Awards/Create
        public async Task<IActionResult> Create()
        {
            // Retrieve the list of artists and songs for the dropdowns
            var artists = await _artistService.GetAllArtistsAsync();
            var songs = await _songService.GetAllSongsAsync();

            ViewBag.Artists = new SelectList(artists, "Id", "Name");
            ViewBag.Songs = new SelectList(songs, "Id", "Title");

            // Pass AwardStatus options to the view
            ViewBag.Statuses = new SelectList(System.Enum.GetValues(typeof(AwardStatus)));

            return View(); // Returns /Views/Awards/Create.cshtml
        }

        // POST: Awards/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Award award)
        {
            if (ModelState.IsValid)
            {
                await _awardService.AddAwardAsync(award);
                return RedirectToAction(nameof(Index));
            }

            // If the model state is invalid, reload the dropdowns
            var artists = await _artistService.GetAllArtistsAsync();
            var songs = await _songService.GetAllSongsAsync();

            ViewBag.Artists = new SelectList(artists, "Id", "Name");
            ViewBag.Songs = new SelectList(songs, "Id", "Title");
            ViewBag.Statuses = new SelectList(System.Enum.GetValues(typeof(AwardStatus)));

            return View(award); // Returns /Views/Awards/Create.cshtml
        }

        // GET: Awards/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var award = await _awardService.GetAwardByIdAsync(id);
            if (award == null)
            {
                return NotFound();
            }

            // Retrieve the list of artists and songs for the dropdowns
            var artists = await _artistService.GetAllArtistsAsync();
            var songs = await _songService.GetAllSongsAsync();

            ViewBag.Artists = new SelectList(artists, "Id", "Name", award.Song?.ArtistId);
            ViewBag.Songs = new SelectList(songs, "Id", "Title", award.SongId);
            ViewBag.Statuses = new SelectList(System.Enum.GetValues(typeof(AwardStatus)), award.Status);

            return View(award); // Returns /Views/Awards/Edit.cshtml
        }

        // POST: Awards/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Award award)
        {
            if (id != award.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _awardService.UpdateAwardAsync(award);
                return RedirectToAction(nameof(Index));
            }

            // If the model state is invalid, reload the dropdowns
            var artists = await _artistService.GetAllArtistsAsync();
            var songs = await _songService.GetAllSongsAsync();

            ViewBag.Artists = new SelectList(artists, "Id", "Name", award.Song?.ArtistId);
            ViewBag.Songs = new SelectList(songs, "Id", "Title", award.SongId);
            ViewBag.Statuses = new SelectList(System.Enum.GetValues(typeof(AwardStatus)), award.Status);

            return View(award); // Returns /Views/Awards/Edit.cshtml
        }

        // GET: Awards/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var award = await _awardService.GetAwardByIdAsync(id);
            if (award == null)
            {
                return NotFound();
            }
            return View(award); // Returns /Views/Awards/Delete.cshtml
        }

        // POST: Awards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _awardService.DeleteAwardAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/SongsController.cs
using Microsoft.AspNetCore.Mvc;
using GrammyAwards.Interfaces;
using GrammyAwards.Models;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace GrammyAwards.Controllers
{
    public class SongsController : Controller
    {
        private readonly ISongService _songService;
        private readonly IArtistService _artistService;

        public SongsController(ISongService songService, IArtistService artistService)
        {
            _songService = songService;
            _artistService = artistService;
        }

        // GET: Songs/Index
        public async Task<IActionResult> Index()
        {
            var songs = await _songService.GetAllSongsAsync();
            return View(songs); // Returns /Views/Songs/Index.cshtml
        }

        // GET: Songs/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var song = await _songService.GetSongByIdAsync(id);
            if (song == null)
            {
                return NotFound();
            }
            return View(song); // Returns /Views/Songs/Details.cshtml
        }

        // GET: Songs/Create
        public async Task<IActionResult> Create()
        {
            // Retrieve the list of artists for the dropdown
            var artists = await _artistService.GetAllArtistsAsync();
            ViewBag.Artists = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(artists, "Id", "Name");
            return View(); // Returns /Views/Songs/Create.cshtml
        }

        // POST: Songs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Song song)
        {
            if (ModelState.IsValid)
            {
                await _songService.AddSongAsync(song);
                return RedirectToAction(nameof(Index));
            }

            // If the model state is invalid, reload the artists dropdown
            var artists = await _artistService.GetAllArtistsAsync();
            ViewBag.Artists = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(artists, "Id", "Name");
            return View(song); // Returns /Views/Songs/Create.cshtml
        }

        // GET: Songs/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var song = await _songService.GetSongByIdAsync(id);
            if (song == null)
            {
                return NotFound();
            }

            // Retrieve the list of artists for the dropdown
            var artists = await _artistService.GetAllArtistsAsync();
            ViewBag.Artists = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(artists, "Id", "Name", song.ArtistId);
            return View(song); // Returns /Views/Songs/Edit.cshtml
        }

        // POST: Songs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Song song)
        {
            if (id != song.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _songService.UpdateSongAsync(song);
                return RedirectToAction(nameof(Index));
            }

            // If the model state is invalid, reload the artists dropdown
            var artists = await _artistService.GetAllArtistsAsync();
            ViewBag.Artists = new Microsoft.AspNetCore.Mvc.Rendering.SelectList(artists, "Id", "Name", song.ArtistId);
            return View(song); // Returns /Views/Songs/Edit.cshtml
        }

        // GET: Songs/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var song = await _songService.GetSongByIdAsync(id);
            if (song == null)
            {
                return NotFound();
            }
            return View(song); // Returns /Views/Songs/Delete.cshtml
        }

        // POST: Songs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _songService.DeleteSongAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GrammyAwards</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GrammyAwards.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
    <style>
        /* Grammy Awards Theme */
        body {
            color: black;
        }

        /* Navbar */
        .navbar {
            background: linear-gradient(90deg, #C89B3C, #7A591E);
        }

        .navbar-brand {
            font-weight: bold;
            font-size: 24px;
            color: #fff !important;
        }

        .nav-link {
            color: #fff !important;
            font-weight: 500;
        }

            .nav-link:hover {
                color: #F5C518 !important;
            }

        /* Hero Section */
        .hero {
            text-align: center;
            padding: 80px 20px;
            background: url('https://upload.wikimedia.org/wikipedia/en/8/8d/Grammy_Award_trophy.png') no-repeat center top;
            background-size: contain;
        }

            .hero h1 {
                font-size: 50px;
                font-weight: bold;
                color: #F5C518;
            }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">🏆 Grammy Awards</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Artists" asp-action="Index">Artists</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Songs" asp-action="Index">Songs</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Awards" asp-action="Index">Awards</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                        <!-- API Navigation Link -->
                        <li class="nav-item"><a class="nav-link" href="/swagger">API Documentation</a></li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="hero">
        <h1>Welcome to the Grammy Awards</h1>
        <p class="lead">Honoring excellence in music since 1959</p>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>